# Google Cloud Build configuration for CHARLY UI
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/charly-ui:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/charly-ui:latest',
      '.'
    ]
    
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/charly-ui:$BUILD_ID']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/charly-ui:latest']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'charly-ui',
      '--image', 'gcr.io/$PROJECT_ID/charly-ui:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--timeout', '300s',
      '--concurrency', '80',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/charly-ui:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/charly-ui:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  
# Timeout for the entire build
timeout: '1200s'