runtime: python39
entrypoint: uvicorn fastapi_backend.main:app --host=0.0.0.0 --port=$PORT

env_variables:
  NODE_ENV: "production"

# App Engine will serve everything through the FastAPI app
# No need for static handlers since FastAPI handles static files
handlers:
  - url: /.*
    script: auto

# Optional: Set instance class for better performance
instance_class: F2

# Optional: Enable automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65