global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # CHARLY Health Service
  - job_name: 'charly-health'
    static_configs:
      - targets: ['charly-health:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # CHARLY Prometheus Native Endpoint
  - job_name: 'charly-prometheus'
    static_configs:
      - targets: ['charly-health:8000']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Add AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093