# Prometheus configuration for LLaMA-3-70B monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add alerting rules here if needed
  # - "alert_rules.yml"

scrape_configs:
  # LLaMA server monitoring
  - job_name: 'llama-server'
    static_configs:
      - targets: ['llama-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Redis cache monitoring
  - job_name: 'redis-cache'
    static_configs:
      - targets: ['redis-cache:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Add alertmanager targets if needed
          # - alertmanager:9093