import type { CommercialPropertyCore } from '@charly/contracts';

export class AppealService {
  async generateAppealPacket(workfileId: string): Promise<Buffer> {
    const mockProperty: Partial<CommercialPropertyCore> = {
      address: {
        street: '123 Business Ave',
        city: 'Anytown',
        state: 'CA',
        zipCode: '90210'
      },
      propertyType: 'office',
      assessedValue: 2500000,
      marketValue: 3000000,
      taxRate: 0.0125
    };

    const pdfContent = this.generateCommercialPDF(mockProperty, workfileId);
    return Buffer.from(pdfContent, 'utf8');
  }

  private generateCommercialPDF(property: Partial<CommercialPropertyCore>, workfileId: string): string {
    const currentDate = new Date().toLocaleDateString();
    
    return `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font << /F1 5 0 R >>
>>
>>
endobj

4 0 obj
<<
/Length 800
>>
stream
BT
/F1 12 Tf
50 750 Td
(COMMERCIAL PROPERTY APPEAL DOSSIER) Tj
0 -30 Td
(Generated by CHARLY Platform) Tj
0 -30 Td
(Date: ${currentDate}) Tj
0 -30 Td
(Workfile ID: ${workfileId}) Tj

0 -50 Td
(PROPERTY INFORMATION) Tj
0 -20 Td
(Address: ${property.address?.street || 'N/A'}) Tj
0 -20 Td
(City: ${property.address?.city || 'N/A'}, ${property.address?.state || 'N/A'} ${property.address?.zipCode || 'N/A'}) Tj
0 -20 Td
(Property Type: ${property.propertyType || 'N/A'}) Tj

0 -30 Td
(ASSESSMENT ANALYSIS) Tj
0 -20 Td
(Current Assessed Value: $${property.assessedValue?.toLocaleString() || 'N/A'}) Tj
0 -20 Td
(Estimated Market Value: $${property.marketValue?.toLocaleString() || 'N/A'}) Tj
0 -20 Td
(Tax Rate: ${((property.taxRate || 0) * 100).toFixed(2)}%) Tj

0 -30 Td
(APPEAL RECOMMENDATION) Tj
0 -20 Td
(Based on our analysis, this property appears to be) Tj
0 -20 Td
(overassessed relative to market value.) Tj

0 -30 Td
(This report was generated by CHARLY's automated) Tj
0 -20 Td
(assessment analysis system. No platform-provided) Tj
0 -20 Td
(comparables are included in this report.) Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000053 00000 n 
0000000125 00000 n 
0000000279 00000 n 
0000001130 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
1200
%%EOF`;
  }
}