# ============================================================================
# CHARLY PLATFORM - PROMETHEUS ALERTING RULES
# Apple CTO Enterprise Monitoring - Phase 3B
# ============================================================================

groups:
  # ============================================================================
  # APPLICATION HEALTH ALERTS
  # ============================================================================
  - name: charly_application_alerts
    rules:
      - alert: ApplicationDown
        expr: up{job=~"charly-.*"} == 0
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "CHARLY Application service is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"
          runbook_url: "https://wiki.charly.com/runbooks/application-down"

      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m])) by (instance, job) /
            sum(rate(http_requests_total[5m])) by (instance, job)
          ) > 0.05
        for: 2m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance, job)
          ) > 2.0
        for: 5m
        labels:
          severity: warning
          component: performance
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 
            node_memory_MemTotal_bytes
          ) > 0.85
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: HighCPUUsage
        expr: |
          100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

  # ============================================================================
  # DATABASE ALERTS
  # ============================================================================
  - name: charly_database_alerts
    rules:
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been down for more than 1 minute"

      - alert: DatabaseConnectionHigh
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "High database connection count"
          description: "Database has {{ $value }} active connections"

      - alert: DatabaseSlowQueries
        expr: pg_stat_activity_max_tx_duration{state="active"} > 300
        for: 2m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Slow database queries detected"
          description: "Longest running query duration is {{ $value }}s"

      - alert: DatabaseDiskSpaceLow
        expr: |
          (
            (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) /
            node_filesystem_size_bytes{mountpoint="/"}
          ) > 0.85
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Database disk space low"
          description: "Database disk usage is {{ $value | humanizePercentage }}"

  # ============================================================================
  # CACHE ALERTS
  # ============================================================================
  - name: charly_cache_alerts
    rules:
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          component: cache
        annotations:
          summary: "Redis cache is down"
          description: "Redis cache has been down for more than 1 minute"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.90
        for: 5m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      - alert: RedisHighConnections
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis high connection count"
          description: "Redis has {{ $value }} connected clients"

  # ============================================================================
  # BUSINESS LOGIC ALERTS
  # ============================================================================
  - name: charly_business_alerts
    rules:
      - alert: LowReportGenerationRate
        expr: |
          rate(charly_reports_generated_total[1h]) < 10
        for: 30m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "Low report generation rate"
          description: "Only {{ $value }} reports generated in the last hour"

      - alert: HighFileProcessingErrors
        expr: |
          (
            rate(charly_file_processing_errors_total[5m]) /
            rate(charly_file_processing_total[5m])
          ) > 0.10
        for: 10m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "High file processing error rate"
          description: "File processing error rate is {{ $value | humanizePercentage }}"

      - alert: PaymentProcessingFailure
        expr: increase(charly_payment_failures_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
          component: business
        annotations:
          summary: "Payment processing failure detected"
          description: "{{ $value }} payment processing failures in the last 5 minutes"

      - alert: UnauthorizedAccessAttempts
        expr: increase(charly_auth_failures_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High authentication failure rate"
          description: "{{ $value }} authentication failures in the last 5 minutes"

  # ============================================================================
  # INFRASTRUCTURE ALERTS
  # ============================================================================
  - name: charly_infrastructure_alerts
    rules:
      - alert: ContainerRestarting
        expr: increase(kube_pod_container_status_restarts_total[15m]) > 0
        for: 0m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Container restarting"
          description: "Container {{ $labels.container }} in pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"

      - alert: DiskSpaceLow
        expr: |
          (
            (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) /
            node_filesystem_size_bytes{fstype!="tmpfs"}
          ) > 0.80
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Disk space low"
          description: "Disk space usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}:{{ $labels.mountpoint }}"

      - alert: NetworkHighLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket{job="traefik"}[5m])) by (le)
          ) > 1.0
        for: 5m
        labels:
          severity: warning
          component: network
        annotations:
          summary: "High network latency"
          description: "95th percentile network latency is {{ $value }}s"

  # ============================================================================
  # SECURITY ALERTS
  # ============================================================================
  - name: charly_security_alerts
    rules:
      - alert: SuspiciousTraffic
        expr: |
          increase(traefik_service_requests_total{code=~"4.."}[5m]) > 100
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High 4xx error rate detected"
          description: "{{ $value }} 4xx errors in the last 5 minutes"

      - alert: DDoSAttackSuspected
        expr: |
          sum(rate(traefik_service_requests_total[1m])) > 1000
        for: 1m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "Possible DDoS attack"
          description: "Request rate is {{ $value }} requests/second"

      - alert: SSLCertificateExpiringSoon
        expr: |
          (traefik_tls_certs_not_after - time()) / 86400 < 7
        for: 1h
        labels:
          severity: warning
          component: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate will expire in {{ $value }} days"