# ============================================================================
# CHARLY PLATFORM - PROMETHEUS CONFIGURATION
# Apple CTO Enterprise Monitoring - Phase 3B
# ============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'charly-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # CHARLY Application Frontend (Nginx)
  - job_name: 'charly-frontend'
    static_configs:
      - targets: ['charly-app:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # CHARLY Application Backend (FastAPI)
  - job_name: 'charly-backend'
    static_configs:
      - targets: ['charly-app:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Traefik Reverse Proxy
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 15s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

# ============================================================================
# RECORDING RULES FOR PERFORMANCE OPTIMIZATION
# ============================================================================
recording_rules:
  - name: charly_performance_rules
    rules:
      # Application Response Time
      - record: charly:response_time_seconds
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, method, route))
      
      # Error Rate
      - record: charly:error_rate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))
      
      # Throughput
      - record: charly:request_rate
        expr: sum(rate(http_requests_total[5m])) by (method, route)
      
      # Database Connection Pool
      - record: charly:db_connections_active
        expr: sum(pg_stat_activity_count) by (instance)
      
      # Memory Usage
      - record: charly:memory_usage_percent
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
      
      # CPU Usage
      - record: charly:cpu_usage_percent
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

# ============================================================================
# ALERTING RULES
# ============================================================================
alerting_rules:
  - name: charly_alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: charly:error_rate > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 2 minutes"
      
      # High Response Time Alert
      - alert: HighResponseTime
        expr: charly:response_time_seconds > 1.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"
      
      # Database Connection Alert
      - alert: DatabaseConnectionHigh
        expr: charly:db_connections_active > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connection count"
          description: "Database has {{ $value }} active connections"
      
      # Memory Usage Alert
      - alert: HighMemoryUsage
        expr: charly:memory_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"
      
      # CPU Usage Alert
      - alert: HighCPUUsage
        expr: charly:cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"
      
      # Service Down Alert
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"