# ============================================================================
# CHARLY PLATFORM - GRAFANA DATASOURCE CONFIGURATION
# Apple CTO Enterprise Monitoring - Phase 3B
# ============================================================================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: '2.45.0'
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: "15s"
      customQueryParameters: ""
    secureJsonData: {}
    version: 1
    uid: prometheus-uid
    
  # Optional: Add PostgreSQL datasource for database monitoring
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: charly_prod
    user: charly
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${DB_PASSWORD}
    version: 1
    uid: postgres-uid